<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.5.0" />

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>66314eb6-f940-4e72-a86c-239d40910aea</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.0" />
		<PackageReference Include="Aspire.Hosting.SqlServer" Version="9.5.0" />
		<PackageReference Include="Aspire.Hosting.Nats" Version="9.5.0" />
		<PackageReference Include="Aspire.NATS.Net" Version="9.5.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bikes.Api.Host\Bikes.Api.Host.csproj" />
		<ProjectReference Include="..\Bikes.Generator.Nats.Host\Bikes.Generator.Nats.Host.csproj" />
		<ProjectReference Include="..\Bikes.ServiceDefaults\Bikes.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>