// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Bikes.Infrastructure.EfCore.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "BikeModels",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Type = table.Column<int>(type: "int", nullable: false),
                    WheelSize = table.Column<double>(type: "float", nullable: false),
                    MaxWeight = table.Column<double>(type: "float", nullable: false),
                    Weight = table.Column<double>(type: "float", nullable: false),
                    BrakeType = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModelYear = table.Column<int>(type: "int", nullable: false),
                    PricePerHour = table.Column<decimal>(type: "decimal(18,2)", precision: 18, scale: 2, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_BikeModels", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Clients",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    LastName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FirstName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MiddleName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Phone = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Clients", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Bikes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    SerialNumber = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Color = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModelId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Bikes", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Bikes_BikeModels_ModelId",
                        column: x => x.ModelId,
                        principalTable: "BikeModels",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Rentals",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    BikeId = table.Column<int>(type: "int", nullable: false),
                    ClientId = table.Column<int>(type: "int", nullable: false),
                    StartTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DurationHours = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Rentals", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Rentals_Bikes_BikeId",
                        column: x => x.BikeId,
                        principalTable: "Bikes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Rentals_Clients_ClientId",
                        column: x => x.ClientId,
                        principalTable: "Clients",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "BikeModels",
                columns: new[] { "Id", "BrakeType", "MaxWeight", "ModelYear", "PricePerHour", "Type", "Weight", "WheelSize" },
                values: new object[,]
                {
                    { 1, "Disc", 120.0, 2023, 15.0m, 3, 9.5, 28.0 },
                    { 2, "Hydraulic", 130.0, 2023, 12.0m, 1, 11.199999999999999, 26.0 },
                    { 3, "Rim", 110.0, 2023, 8.0m, 2, 10.800000000000001, 27.5 },
                    { 4, "Caliper", 100.0, 2023, 18.0m, 0, 7.7999999999999998, 28.0 },
                    { 5, "Disc", 125.0, 2024, 20.0m, 3, 8.9000000000000004, 29.0 },
                    { 6, "Disc", 120.0, 2023, 25.0m, 4, 18.5, 26.0 },
                    { 7, "U-Brake", 90.0, 2023, 10.0m, 5, 10.199999999999999, 20.0 },
                    { 8, "Rim", 80.0, 2023, 12.0m, 3, 7.5, 24.0 },
                    { 9, "Hydraulic", 135.0, 2024, 14.0m, 1, 12.1, 27.5 },
                    { 10, "Caliper", 95.0, 2023, 16.0m, 0, 7.2000000000000002, 28.0 }
                });

            migrationBuilder.InsertData(
                table: "Clients",
                columns: new[] { "Id", "FirstName", "LastName", "MiddleName", "Phone" },
                values: new object[,]
                {
                    { 1, "Ivan", "Petrov", "Sergeevich", "+7-911-111-11-11" },
                    { 2, "Maria", "Ivanova", "Alexandrovna", "+7-922-222-22-22" },
                    { 3, "Alexey", "Sidorov", "Vladimirovich", "+7-933-333-33-33" },
                    { 4, "Elena", "Kuznetsova", "Dmitrievna", "+7-944-444-44-44" },
                    { 5, "Dmitry", "Smirnov", "Igorevich", "+7-955-555-55-55" },
                    { 6, "Olga", "Popova", "Sergeevna", "+7-966-666-66-66" },
                    { 7, "Sergey", "Vasiliev", "Petrovich", "+7-977-777-77-77" },
                    { 8, "Anna", "Novikova", "Andreevna", "+7-988-888-88-88" },
                    { 9, "Pavel", "Fedorov", "Nikolaevich", "+7-999-999-99-99" },
                    { 10, "Natalya", "Morozova", "Viktorovna", "+7-900-000-00-00" }
                });

            migrationBuilder.InsertData(
                table: "Bikes",
                columns: new[] { "Id", "Color", "ModelId", "SerialNumber" },
                values: new object[,]
                {
                    { 1, "Red", 1, "SN000001" },
                    { 2, "Blue", 2, "SN000002" },
                    { 3, "Green", 3, "SN000003" },
                    { 4, "Black", 4, "SN000004" },
                    { 5, "White", 5, "SN000005" },
                    { 6, "Yellow", 6, "SN000006" },
                    { 7, "Silver", 7, "SN000007" },
                    { 8, "Orange", 8, "SN000008" },
                    { 9, "Purple", 9, "SN000009" },
                    { 10, "Red", 10, "SN000010" }
                });

            migrationBuilder.InsertData(
                table: "Rentals",
                columns: new[] { "Id", "BikeId", "ClientId", "DurationHours", "StartTime" },
                values: new object[,]
                {
                    { 1, 1, 1, 10, new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 2, 1, 2, 5, new DateTime(2024, 1, 12, 14, 30, 0, 0, DateTimeKind.Unspecified) },
                    { 3, 1, 3, 8, new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 4, 2, 4, 12, new DateTime(2024, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 5, 2, 5, 6, new DateTime(2024, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 6, 2, 6, 3, new DateTime(2024, 1, 22, 13, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 7, 3, 7, 7, new DateTime(2024, 1, 25, 15, 30, 0, 0, DateTimeKind.Unspecified) },
                    { 8, 3, 8, 9, new DateTime(2024, 1, 28, 9, 30, 0, 0, DateTimeKind.Unspecified) },
                    { 9, 4, 9, 2, new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 10, 4, 10, 4, new DateTime(2024, 2, 3, 17, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 11, 5, 1, 15, new DateTime(2024, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 12, 5, 1, 8, new DateTime(2024, 2, 8, 14, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 13, 6, 1, 6, new DateTime(2024, 2, 10, 16, 30, 0, 0, DateTimeKind.Unspecified) },
                    { 14, 7, 1, 11, new DateTime(2024, 2, 12, 11, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 15, 8, 2, 1, new DateTime(2024, 2, 15, 13, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 16, 9, 2, 5, new DateTime(2024, 2, 18, 15, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 17, 10, 2, 20, new DateTime(2024, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 18, 10, 6, 12, new DateTime(2024, 2, 22, 12, 30, 0, 0, DateTimeKind.Unspecified) },
                    { 19, 10, 6, 8, new DateTime(2024, 2, 25, 14, 0, 0, 0, DateTimeKind.Unspecified) },
                    { 20, 10, 3, 10, new DateTime(2024, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified) }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Bikes_ModelId",
                table: "Bikes",
                column: "ModelId");

            migrationBuilder.CreateIndex(
                name: "IX_Bikes_SerialNumber",
                table: "Bikes",
                column: "SerialNumber",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Rentals_BikeId",
                table: "Rentals",
                column: "BikeId");

            migrationBuilder.CreateIndex(
                name: "IX_Rentals_ClientId",
                table: "Rentals",
                column: "ClientId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Rentals");

            migrationBuilder.DropTable(
                name: "Bikes");

            migrationBuilder.DropTable(
                name: "Clients");

            migrationBuilder.DropTable(
                name: "BikeModels");
        }
    }
}
