// <auto-generated />
using System;
using Bikes.Infrastructure.EfCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bikes.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bikes.Core.Entities.Bike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Bikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Red",
                            ModelId = 1,
                            SerialNumber = "SN000001"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Blue",
                            ModelId = 2,
                            SerialNumber = "SN000002"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Green",
                            ModelId = 3,
                            SerialNumber = "SN000003"
                        },
                        new
                        {
                            Id = 4,
                            Color = "Black",
                            ModelId = 4,
                            SerialNumber = "SN000004"
                        },
                        new
                        {
                            Id = 5,
                            Color = "White",
                            ModelId = 5,
                            SerialNumber = "SN000005"
                        },
                        new
                        {
                            Id = 6,
                            Color = "Yellow",
                            ModelId = 6,
                            SerialNumber = "SN000006"
                        },
                        new
                        {
                            Id = 7,
                            Color = "Silver",
                            ModelId = 7,
                            SerialNumber = "SN000007"
                        },
                        new
                        {
                            Id = 8,
                            Color = "Orange",
                            ModelId = 8,
                            SerialNumber = "SN000008"
                        },
                        new
                        {
                            Id = 9,
                            Color = "Purple",
                            ModelId = 9,
                            SerialNumber = "SN000009"
                        },
                        new
                        {
                            Id = 10,
                            Color = "Red",
                            ModelId = 10,
                            SerialNumber = "SN000010"
                        });
                });

            modelBuilder.Entity("Bikes.Core.Entities.BikeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrakeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<int>("ModelYear")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.Property<double>("WheelSize")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BikeModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrakeType = "Disc",
                            MaxWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 15.0m,
                            Type = 3,
                            Weight = 9.5,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = 2,
                            BrakeType = "Hydraulic",
                            MaxWeight = 130.0,
                            ModelYear = 2023,
                            PricePerHour = 12.0m,
                            Type = 1,
                            Weight = 11.199999999999999,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = 3,
                            BrakeType = "Rim",
                            MaxWeight = 110.0,
                            ModelYear = 2023,
                            PricePerHour = 8.0m,
                            Type = 2,
                            Weight = 10.800000000000001,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = 4,
                            BrakeType = "Caliper",
                            MaxWeight = 100.0,
                            ModelYear = 2023,
                            PricePerHour = 18.0m,
                            Type = 0,
                            Weight = 7.7999999999999998,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = 5,
                            BrakeType = "Disc",
                            MaxWeight = 125.0,
                            ModelYear = 2024,
                            PricePerHour = 20.0m,
                            Type = 3,
                            Weight = 8.9000000000000004,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = 6,
                            BrakeType = "Disc",
                            MaxWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 25.0m,
                            Type = 4,
                            Weight = 18.5,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = 7,
                            BrakeType = "U-Brake",
                            MaxWeight = 90.0,
                            ModelYear = 2023,
                            PricePerHour = 10.0m,
                            Type = 5,
                            Weight = 10.199999999999999,
                            WheelSize = 20.0
                        },
                        new
                        {
                            Id = 8,
                            BrakeType = "Rim",
                            MaxWeight = 80.0,
                            ModelYear = 2023,
                            PricePerHour = 12.0m,
                            Type = 3,
                            Weight = 7.5,
                            WheelSize = 24.0
                        },
                        new
                        {
                            Id = 9,
                            BrakeType = "Hydraulic",
                            MaxWeight = 135.0,
                            ModelYear = 2024,
                            PricePerHour = 14.0m,
                            Type = 1,
                            Weight = 12.1,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = 10,
                            BrakeType = "Caliper",
                            MaxWeight = 95.0,
                            ModelYear = 2023,
                            PricePerHour = 16.0m,
                            Type = 0,
                            Weight = 7.2000000000000002,
                            WheelSize = 28.0
                        });
                });

            modelBuilder.Entity("Bikes.Core.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            MiddleName = "Sergeevich",
                            Phone = "+7-911-111-11-11"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Maria",
                            LastName = "Ivanova",
                            MiddleName = "Alexandrovna",
                            Phone = "+7-922-222-22-22"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Alexey",
                            LastName = "Sidorov",
                            MiddleName = "Vladimirovich",
                            Phone = "+7-933-333-33-33"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Elena",
                            LastName = "Kuznetsova",
                            MiddleName = "Dmitrievna",
                            Phone = "+7-944-444-44-44"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Dmitry",
                            LastName = "Smirnov",
                            MiddleName = "Igorevich",
                            Phone = "+7-955-555-55-55"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Olga",
                            LastName = "Popova",
                            MiddleName = "Sergeevna",
                            Phone = "+7-966-666-66-66"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Sergey",
                            LastName = "Vasiliev",
                            MiddleName = "Petrovich",
                            Phone = "+7-977-777-77-77"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Anna",
                            LastName = "Novikova",
                            MiddleName = "Andreevna",
                            Phone = "+7-988-888-88-88"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Pavel",
                            LastName = "Fedorov",
                            MiddleName = "Nikolaevich",
                            Phone = "+7-999-999-99-99"
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Natalya",
                            LastName = "Morozova",
                            MiddleName = "Viktorovna",
                            Phone = "+7-900-000-00-00"
                        });
                });

            modelBuilder.Entity("Bikes.Core.Entities.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BikeId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BikeId = 1,
                            ClientId = 1,
                            DurationHours = 10,
                            StartTime = new DateTime(2024, 1, 10, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BikeId = 1,
                            ClientId = 2,
                            DurationHours = 5,
                            StartTime = new DateTime(2024, 1, 12, 14, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BikeId = 1,
                            ClientId = 3,
                            DurationHours = 8,
                            StartTime = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BikeId = 2,
                            ClientId = 4,
                            DurationHours = 12,
                            StartTime = new DateTime(2024, 1, 18, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BikeId = 2,
                            ClientId = 5,
                            DurationHours = 6,
                            StartTime = new DateTime(2024, 1, 20, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BikeId = 2,
                            ClientId = 6,
                            DurationHours = 3,
                            StartTime = new DateTime(2024, 1, 22, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BikeId = 3,
                            ClientId = 7,
                            DurationHours = 7,
                            StartTime = new DateTime(2024, 1, 25, 15, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BikeId = 3,
                            ClientId = 8,
                            DurationHours = 9,
                            StartTime = new DateTime(2024, 1, 28, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BikeId = 4,
                            ClientId = 9,
                            DurationHours = 2,
                            StartTime = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BikeId = 4,
                            ClientId = 10,
                            DurationHours = 4,
                            StartTime = new DateTime(2024, 2, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BikeId = 5,
                            ClientId = 1,
                            DurationHours = 15,
                            StartTime = new DateTime(2024, 2, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BikeId = 5,
                            ClientId = 1,
                            DurationHours = 8,
                            StartTime = new DateTime(2024, 2, 8, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BikeId = 6,
                            ClientId = 1,
                            DurationHours = 6,
                            StartTime = new DateTime(2024, 2, 10, 16, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BikeId = 7,
                            ClientId = 1,
                            DurationHours = 11,
                            StartTime = new DateTime(2024, 2, 12, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BikeId = 8,
                            ClientId = 2,
                            DurationHours = 1,
                            StartTime = new DateTime(2024, 2, 15, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BikeId = 9,
                            ClientId = 2,
                            DurationHours = 5,
                            StartTime = new DateTime(2024, 2, 18, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BikeId = 10,
                            ClientId = 2,
                            DurationHours = 20,
                            StartTime = new DateTime(2024, 2, 20, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BikeId = 10,
                            ClientId = 6,
                            DurationHours = 12,
                            StartTime = new DateTime(2024, 2, 22, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BikeId = 10,
                            ClientId = 6,
                            DurationHours = 8,
                            StartTime = new DateTime(2024, 2, 25, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BikeId = 10,
                            ClientId = 3,
                            DurationHours = 10,
                            StartTime = new DateTime(2024, 2, 28, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bikes.Core.Entities.Bike", b =>
                {
                    b.HasOne("Bikes.Core.Entities.BikeModel", "Model")
                        .WithMany("Bikes")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Bikes.Core.Entities.Rental", b =>
                {
                    b.HasOne("Bikes.Core.Entities.Bike", "Bike")
                        .WithMany("Rentals")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bikes.Core.Entities.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Bikes.Core.Entities.Bike", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("Bikes.Core.Entities.BikeModel", b =>
                {
                    b.Navigation("Bikes");
                });

            modelBuilder.Entity("Bikes.Core.Entities.Client", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
