<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.22" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Aspire.NATS.Net" Version="9.5.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Bikes.Application\Bikes.Application.csproj" />
		<ProjectReference Include="..\Bikes.Infrastructure.EfCore\Bikes.Infrastructure.EfCore.csproj" />
		<ProjectReference Include="..\Bikes.Infrastructure.Nats\Bikes.Infrastructure.Nats.csproj" />
		<ProjectReference Include="..\Bikes.Validator.Nats\Bikes.Validator.Nats.csproj" />
		<ProjectReference Include="..\Bikes.ServiceDefaults\Bikes.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>